services:
  - type: web
    name: sih-health-app
    env: python
    plan: free
    buildCommand: ""
    startCommand: python server/app.py
    envVars:
      - key: FLASK_ENV
        value: production
    autoDeploy: true
